name: Bug Issue Template
description: An Issue Template for Bugs
title: "[BUG] "
labels: []
assignees: []
body:
  - type: textarea
    attributes:
      label: Description
      description: Describe the bug
      placeholder: Describe the bug
    validations:
      required: true
  - type: textarea
    attributes:
      label: How to reproduce
      description: List of todos
      placeholder: |
        1. Step 1: 
        2. Step 2:
      value: |
        1.
    validations:
      required: false
  - type: textarea
    attributes:
      label: ETC
      description: ETC
      placeholder: ETC
    validations:
      required: false
