name: Feature Issue Template
description: An Issue Template for Features
title: "[FEATURE] "
labels: []
assignees: []
body:
  - type: textarea
    attributes:
      label: Description
      description: Describe the feature
      placeholder: Describe the feature
    validations:
      required: true
  - type: textarea
    attributes:
      label: Todos
      description: List of todos
      placeholder: |
        - [ ] Todo 1
        - [ ] Todo 2
        - [ ] Todo 3
    validations:
      required: false
  - type: textarea
    attributes:
      label: ETC
      description: ETC
      placeholder: ETC
    validations:
      required: false
